const { KlasaClient } = require("klasa");

module.exports = KlasaClient.defaultUserSchema
    .add("level", folder => folder
        .add("xp", "integer", { default: 0, configurable: false })
        .add("current", "integer", { default: 1, configurable: false })
        .add("cooldown", "integer", { default: 0, configurable: false }))

    .add("keys", folder => folder
        .add("stn", "string", { default: "0;0", configurable: false })
        .add("dns", "string", { default: "", configurable: false })
        .add("assigns", "string", { default: "", configurable: false })
        .add("bal", "integer", { default: 0, configurable: false })
        .add("bio", "string", { default: "", configurable: false })
        .add("blacklist", "string", { default: "", configurable: false })
        .add("chillpills", "integer", { default: 0, configurable: false })
        .add("chnl", "string", { default: "", configurable: false })
        .add("clr", "string", { default: "#00aaaa", configurable: false })
        .add("cmds", "integer", { default: 0, configurable: false })
        .add("crdt", "integer", { default: 0, configurable: false  })
        .add("cst", "string", { default: "", configurable: false })
        .add("curralias", "string", { default: "", configurable: false  })
        .add("debug", "string", { default: "", configurable: false  })
        .add("deldatareqed", "string", { default: "", configurable: false  })
        .add("curralias", "string", { default: "", configurable: false  })
        .add("dialc", "integer", { default: 0, configurable: false  })
        .add("dlc", "integer", { default: 0, configurable: false  })
        .add("dose0", "integer", { default: 0, configurable: false  })
        .add("dprvc", "integer", { default: 0, configurable: false  })
        .add("dwngrdc", "integer", { default: 0, configurable: false  })
        .add("fdc", "integer", { default: 0, configurable: false  })
        .add("fishc", "integer", { default: 0, configurable: false  })
        .add("fsh", "string", { default: "0;0;0;0;0;0", configurable: false  })
        .add("hgs", "integer", { default: 0, configurable: false  })
        .add("infcs", "integer", { default: 0, configurable: false  })
        // .add("mute", "object", { default: {  }, configurable: false  })
        .add("nick", "string", { default: "", configurable: false  })
        .add("noComma", "integer", { default: 0, configurable: false  })
        .add("number", "string", { default: "", configurable: false  })
        .add("ofncs", "string", { default: "0;0;0;0;0;0;0;0;0;0;0;0;0;0;0", configurable: false  })
        .add("perms", "string", { default: "0;0;0;0;0;0;0;0;0;0;0;0", configurable: false  })
        .add("persist", "string", { default: "801010428582297640", configurable: false  })
        .add("pet", "string", { default: "", configurable: false  })
        .add("petbu", "string", { default: "1;1;1;1;1;1;1;1;1;1;1;1", configurable: false  })
        .add("petname", "string", { default: "pet", configurable: false  })
        // .add("replacers", "object", { default: {  }, configurable: false  })
        .add("robc", "integer", { default: 0, configurable: false  })        
        // .add("role", "object", { default: {  }, configurable: false  })
        .add("sentc", "integer", { default: 0, configurable: false  })
        .add("sgstc", "integer", { default: 0, configurable: false  })
        .add("spouse", "string", { default: "", configurable: false  })
        .add("srchc", "integer", { default: 0, configurable: false  })
        .add("strokec", "integer", { default: 0, configurable: false  })
        .add("stunmsg", "string", { default: "You can't use any commands while you're stunned! ($time)", configurable: false  })
        .add("v", "string", { default: "1;0", configurable: false  })
        .add("xp", "integer", { default: 0, configurable: false  })
        .add("xpc", "integer", { default: 0, configurable: false  })
        .add("xplvl", "integer", { default: 0, configurable: false  })
        )